### ISSUE TITLE
config.rs的Keymap和Window未生效

### ISSUE THREAD

**Issue by SchneeHertz** [rsuu/rmg#3]
我修改位于AppData\Roaming\rmg的config文件中Base的部分，可以正常反应在软件上，比如反转鼠标滚轮，调整窗口大小等
但修改Keymap的按键映射，Window的边框设置均不生效
```rust
fn main() {
    Base {
        size: (1440, 2040),    // width AND height
        font: None,          //
        rename_pad: 6,       //
        invert_mouse: true, //
        filter: "Lanczos3",  // [Box, Hamming, Lanczos3, CatmullRom, Mitchell]
        step: 4,             //
    };

    Keymap {
        up: 'k',
        down: 'n',
        left: 'h',
        right: 'l',
        exit: 'q',
    };

    Window {
        borderless: false,
        topmost: true,
        resize: true,
        none: false,
    }
}
```

**Comment by rsuu** [comment]
borderless的话可能需要里自己编译一下代码做测试,我测试不了(你在 WindowOptions 里加个 borderless: true, 然后编译试试看)
> https://github.com/emoon/rust_minifb/blob/master/examples/topmost.rs

keymap这一块过几天我再看看吧,最近感冒了

**Comment by SchneeHertz** [comment]
> borderless的话可能需要里自己编译一下代码做测试,我测试不了(你在 WindowOptions 里加个 borderless: true, 然后编译试试看)
> 
> > https://github.com/emoon/rust_minifb/blob/master/examples/topmost.rs
> 
> keymap这一块过几天我再看看吧,最近感冒了

borderless用命令行参数是可以的，只是配置文件不行

**Comment by rsuu** [comment]
我配置文件写错了  需要更新一下
