### ISSUE TITLE
Install error through cargo

### ISSUE THREAD

**Issue by tokisuno** [rsuu/rmg#5]
Caused by:
  failed to select a version for the requirement `tracing = "^0.1.38"`
  candidate versions found which didn't match: 0.1.37, 0.1.36, 0.1.35, ...
  location searched: crates.io index
  required by package `rmg v0.5.11`
  perhaps a crate was updated and forgotten to be re-vendored?

**Comment by tokisuno** [comment]
built fine through git clone

**Comment by rsuu** [comment]
Well, 0.1.38 was yanked.
I will fix it in 0.5.12.

https://lib.rs/crates/tracing/versions
