### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` ...

### ISSUE THREAD

**Issue by tokisuno** [rsuu/rmg#6]
howdy
```fish
Open: /home/skinnyboot/downloads/Mix v01_11/Mix v01.rar
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to create window, "Failed to setup X IM via XOpenIM."', src/render/window.rs:36:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, './rmg ~/downloads/Mix\ v01_11/M…' terminated by signal SIGABRT (Abort)
```

seems to relate to alacritty judging by [here](https://github.com/alacritty/alacritty/issues/830) and [here](https://github.com/rust-windowing/winit/issues/277), which is a bit annoying.

**Comment by rsuu** [comment]
Could you please show me your cargo build command?
And try `cargo run -F wayland` if you are using Wayland, or switch to 0.5.11.

NOTE: `.rar` is now unsupported.

https://github.com/rsuu/rmg/releases/tag/v0.5.11

**Comment by tokisuno** [comment]
i am using x11. i also didn't know that .rar is unsupported. 

all i did was run ```cargo run```

**Comment by rsuu** [comment]
You could try starting X11 in tty and cargo run again.

```bash
# 1. in tty2: Ctrl + Alt + F2
startx ~/.xinitrc
# or
startx /usr/bin/<VM>

# 2. 
cargo run -- <file>

# 3. in tty1: Ctrl + Alt + F1
# see what happens
```

```test
# xinitrc

# window manager
# e.g. exec i3
exec <VM>

```
